--settings
require("settings")
require("keymaps")
--plugins
require("config.lazy")
require("mason").setup()
require("config.cmp")
require("config.telescope")
require("config.oil")
--theme
require("theme")
